# Generated by Django 4.2.30 on 2026-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('bus_type', models.CharField(choices=[('ordinary', 'Ordinary'), ('express', 'Express'), ('deluxe', 'Deluxe'), ('ac', 'AC')], max_length=50)),
                ('frequency', models.CharField(help_text='e.g., Daily, Mon-Fri, etc.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beaches_count', models.IntegerField(default=12, help_text='Number of beaches')),
                ('matrimony_profiles', models.IntegerField(default=500, help_text='Number of matrimony profiles')),
                ('events_per_year', models.IntegerField(default=50, help_text='Events per year')),
                ('local_vendors', models.IntegerField(default=200, help_text='Number of local vendors')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Statistics',
                'verbose_name_plural': 'Site Statistics',
            },
        ),
    ]
