# Generated by Django 4.2.30 on 2026-05-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(default='Karwar District League', max_length=200)),
                ('team1_name', models.CharField(max_length=100)),
                ('team1_score', models.CharField(blank=True, default='', max_length=50)),
                ('team1_overs', models.CharField(blank=True, default='', max_length=20)),
                ('team2_name', models.CharField(max_length=100)),
                ('team2_score', models.CharField(blank=True, default='', max_length=50)),
                ('team2_overs', models.CharField(blank=True, default='', max_length=20)),
                ('toss_winner', models.CharField(blank=True, default='', max_length=100)),
                ('toss_decision', models.CharField(blank=True, choices=[('bat', 'Bat'), ('bowl', 'Bowl')], max_length=20)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('match_date', models.DateTimeField()),
                ('overs_limit', models.IntegerField(default=20, help_text='Total overs per side')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('result_text', models.CharField(blank=True, default='', max_length=300)),
                ('current_batsman', models.CharField(blank=True, default='', max_length=100)),
                ('current_bowler', models.CharField(blank=True, default='', max_length=100)),
                ('last_commentary', models.TextField(blank=True, default='', help_text='Ball-by-ball updates')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cricket Match',
                'verbose_name_plural': 'Cricket Matches',
                'ordering': ['-match_date'],
            },
        ),
    ]
