# Generated by Django 4.2.30 on 2026-05-30 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cricketmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.IntegerField(choices=[(1, '1st Innings'), (2, '2nd Innings')])),
                ('batting_team', models.CharField(blank=True, default='', max_length=100)),
                ('total_runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs', models.CharField(blank=True, default='0', max_length=10)),
                ('extras', models.IntegerField(default=0)),
                ('extras_detail', models.CharField(blank=True, default='', help_text='e.g. b 0, lb 2, w 5, nb 1', max_length=200)),
                ('current_run_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('required_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status_text', models.CharField(blank=True, default='', help_text='e.g. CSK need 45 runs in 30 balls', max_length=300)),
                ('result', models.CharField(blank=True, default='', help_text='e.g. CSK won by 5 wickets', max_length=300)),
                ('fall_of_wickets', models.TextField(blank=True, default='', help_text='e.g. 1-25 (Rohit, 3.2), 2-48 (SKY, 6.1)')),
                ('batting_data', models.JSONField(blank=True, default=list, help_text='JSON array of batter objects')),
                ('bowling_data', models.JSONField(blank=True, default=list, help_text='JSON array of bowler objects')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_set2', to='core.cricketmatch')),
            ],
            options={
                'verbose_name': 'Innings',
                'verbose_name_plural': 'Innings',
                'ordering': ['innings_number'],
                'unique_together': {('match', 'innings_number')},
            },
        ),
    ]
