# Generated by Django 4.2.30 on 2026-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_innings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrimonyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('height', models.CharField(blank=True, help_text='e.g., 5\'8"', max_length=20)),
                ('caste', models.CharField(choices=[('Gowda', 'Gowda'), ('Bhandari', 'Bhandari'), ('Gunagi', 'Gunagi'), ('Ambig', 'Ambig'), ('Konkan Maratha', 'Konkan Maratha'), ('Kombarpath', 'Kombarpath'), ('Harikantra', 'Harikantra'), ('Sonar', 'Sonar'), ('Brahman', 'Brahman'), ('Dalvi', 'Dalvi'), ('Gabith', 'Gabith'), ('Nadar', 'Nadar'), ('Other', 'Other')], max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matrimony Profile',
                'verbose_name_plural': 'Matrimony Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
